import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import joblib

from config import RAW_DATA_DIR, PROCESSED_DATA_DIR, MODEL_DIR

def build_features():
    print("Loading raw relational data...")
    assets = pd.read_csv(RAW_DATA_DIR / "assets.csv")
    vulns = pd.read_csv(RAW_DATA_DIR / "vulnerabilities.csv")
    incidents = pd.read_csv(RAW_DATA_DIR / "incidents.csv")
    
    # 1. Aggregate Vulnerabilities per asset (1:N -> 1:1 for ML features)
    print("Aggregating vulnerabilities...")
    vuln_features = vulns.groupby("asset_id").agg(
        vuln_count=("vuln_id", "count"),
        critical_vuln_count=("cvss_score", lambda x: (x >= 9.0).sum()),
        max_cvss=("cvss_score", "max"),
        mean_cvss=("cvss_score", "mean"),
        max_epss=("epss_score", "max")
    ).reset_index()
    
    # 2. Merge everything
    df = assets.merge(vuln_features, on="asset_id", how="left")
    df = df.merge(incidents, on="asset_id", how="left")
    
    # Strictly remove any redundant/duplicate records generated by the relational joins
    print(f"Original row count: {len(df)}")
    df = df.drop_duplicates(subset=["asset_id"], keep="first")
    print(f"Row count after removing redundancies: {len(df)}")
    
    # Fill NAs for assets with no vulnerabilities
    vuln_cols = ["vuln_count", "critical_vuln_count", "max_cvss", "mean_cvss", "max_epss"]
    df[vuln_cols] = df[vuln_cols].fillna(0)
    
    # 3. Handle Categoricals
    print("Encoding categorical variables...")
    categorical_cols = ["asset_type", "business_unit"]
    
    # We use pandas get_dummies for simplicity, but in production use scikit-learn OneHotEncoder
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
    
    # Separate features and targets
    drop_cols = ["asset_id", "asset_name", "incident_occurred", "total_loss_inr"]
    X = df.drop(columns=drop_cols)
    y_incident = df["incident_occurred"]
    y_loss = df["total_loss_inr"]
    
    # 4. Train-Test Split (Prevent Data Leakage)
    print("Splitting data into train/test sets...")
    X_train, X_test, y_inc_train, y_inc_test, y_loss_train, y_loss_test = train_test_split(
        X, y_incident, y_loss, test_size=0.2, random_state=42, stratify=y_incident
    )
    
    # 5. Scale numerical features
    print("Scaling numerical features...")
    num_cols = ["asset_criticality_score", "data_sensitivity_score", "revenue_dependency_score", 
                "asset_value_inr", "hourly_downtime_cost_inr", "failed_logins", "anomaly_count"] + vuln_cols
                
    scaler = StandardScaler()
    X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
    X_test[num_cols] = scaler.transform(X_test[num_cols])
    
    # Save the scaler for inference later
    joblib.dump(scaler, MODEL_DIR / "feature_scaler.pkl")
    
    # Save processed datasets
    print(f"Saving processed data to {PROCESSED_DATA_DIR}...")
    X_train.to_csv(PROCESSED_DATA_DIR / "X_train.csv", index=False)
    X_test.to_csv(PROCESSED_DATA_DIR / "X_test.csv", index=False)
    y_inc_train.to_csv(PROCESSED_DATA_DIR / "y_inc_train.csv", index=False)
    y_inc_test.to_csv(PROCESSED_DATA_DIR / "y_inc_test.csv", index=False)
    y_loss_train.to_csv(PROCESSED_DATA_DIR / "y_loss_train.csv", index=False)
    y_loss_test.to_csv(PROCESSED_DATA_DIR / "y_loss_test.csv", index=False)
    
    # Save feature names
    joblib.dump(X_train.columns.tolist(), MODEL_DIR / "feature_names.pkl")
    print("Feature Engineering Complete.")

if __name__ == "__main__":
    build_features()
